### ISSUE TITLE
Versions should display nicely in the filesystem

### ISSUE THREAD

**Issue by ahall** [ahall/Sector#1]
As files are edited directly in the filesystem and not through Sector.Tool, we should be able to name the migrations 001_upgrade 001_downgrade e.g. pad them with 0 so they sort correctly when doing a directory listing. This is the way sqlalchemy-migrate works.

**Comment by ahall** [comment]
Closed by 3e35742161ff5cc863e3f8799f1d4f19c50c68c7

Signed-off-by: Alfred Hall &lt;ahall@ahall.org&gt;

**Comment by AbstractsMachine** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
imnisen, @rohit-nair, @kofikong, @daviogg, @22388o, @posquit0, @ibrahimsn98, @buzzki11, @eilinge, @MarkTangJs, @HadesOK, @sheghun, @jrick, @jese1987, @zuoguoji, @tanel, @thi-investax, @AlbertChanX, @benjaminvanrenterghem, @donghquinn, @qianchong88, @hzxiao, @xiewei-wayne, @aronet56, @alexzel, @mjgil, @Bjorn248, @bitcoinsfacil, @Jimweb3, @UallenQbit, @hnq90, @OGFris, @zergon321, @jonas747, @syafiqrokman, @abanoubha, @qianguozheng, @softhardware, @facert, @JoeByte, @RoestVrijStaal, @oliversong, @Tarunadityaselva, @baryon, @firstrow, @star001007, @diop, @josephawallace, @quantlord, @yuzushiohchenrulongmaster, @lazyman01, @mjgil, @monomania, @joshua2049, @anjmao, @andersonmiranda-com, @madskrogh, @zhouzhuojie, @cavapoo2, @peterwillcn, @debuggor, @julian-goldsmith, @miguelmota, @liexusong, @kmlroot, @mohamedawnallah, @aksiksi, @talesmousinho, @sapk, @wildownes, @luogang0, @tsonglew, @YusukeShimizu, @BugBang, @denisse-dev, @linsanityHuang, @nowa, @suciuvlad, @forrest001, @mohmmadi123, @jese1987, @weiyanwuda, @aabizri, @niallyoung, @zannet, @cooldog21, @lixey, @blup, @onestarshang, @futoase, @emurmotol, @BooBSD, @hnhychlcool2, @nathanph, @caivega, @masoudjooon, @felipefrizzo, @srw, @Alexintoshudhos, @kineticrootkit, @Juffawwaa, @Crypt-iQ, @discosultan, @itbellissimo, @gmartelly, @roman-mc, @lotus-king, @NexZhu, @aerth, @ibrahimsn98, @oliversong, @ligulfzhou, @GreenLim, @abhishekgahlot, @super-l, @ktfth, @wuyuting, @LasTshaMAN, @Jeiwan, @edtk, @xiamingxing, @Mr-Gash, @AarenWang, @plwalters, @lamengao, @cagatay, @dawsbot, @xiewei-wayne, @rohit-nair, @Minkhail, @designermiran, @shripadk, @ndrchvzz, @tp-life, @mehdieidi, @talesmousinho, @seem-sky, @Johnson1s, @lixey, @Garoth, @andrewhummus, @manhvt08b, @aksiksi, @chptx, @JoeByte, @old101, @sonemaro, @denji
